all:
	g++ -m64 -O2 -Wall -std=c++14 -g -o solve main.cpp
gurobi:
	g++ -m64 -O2 -Wall -std=c++14 -g -o solve main.cpp -I /Library/gurobi900/mac64/include/ -L /Library/gurobi900/mac64/lib/ -lgurobi_c++ -lgurobi90 -lm
